SELECT COUNT(*) FROM TABELA_DE_CLIENTES;
-- 16 CLIENTES

SELECT COUNT(*) FROM TABELA_DE_VENDEDORES;
-- 4 VENDEDORES


-- Qual vendedor não tem cliente no bairro?
SELECT DISTINCT
TV.NOME AS NOME_DO_VENDEDOR,
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.BAIRRO AS BAIRRO_DO_CLIENTE,
TC.NOME AS NOME_DO_CLIENTE
FROM
TABELA_DE_CLIENTES TC
RIGHT JOIN
TABELA_DE_VENDEDORES TV
ON TC.BAIRRO = TV.BAIRRO
WHERE TC.NOME IS NULL;


-- Qual cliente não tem vendedor no bairro?

SELECT DISTINCT
TV.NOME AS NOME_DO_VENDEDOR,
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.BAIRRO AS BAIRRO_DO_CLIENTE,
TC.NOME AS NOME_DO_CLIENTE
FROM
TABELA_DE_CLIENTES TC
LEFT JOIN
TABELA_DE_VENDEDORES TV
ON TC.BAIRRO = TV.BAIRRO
WHERE TV.NOME IS NULL ;


SELECT DISTINCT
TV.NOME AS NOME_DO_VENDEDOR,
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.BAIRRO AS BAIRRO_DO_CLIENTE,
TC.NOME AS NOME_DO_CLIENTE
FROM
TABELA_DE_CLIENTES TC
FULL JOIN
TABELA_DE_VENDEDORES TV
ON TC.BAIRRO = TV.BAIRRO;