-- Union aplica o distinct
-- union all para não ocorrer isso

SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES;
--12


SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;
--4


SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES
UNION 
SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;


SELECT DISTINCT BAIRRO, 'CLIENTE' AS ORIGEM FROM TABELA_DE_CLIENTES 
UNION 
SELECT DISTINCT BAIRRO, 'FORNECEDOR' AS ORIGEM FROM TABELA_DE_VENDEDORES;
