SELECT NF.CPF,CONVERT(VARCHAR(7),NF.DATA_VENDA,120) AS MES_ANO, SUM(INF.QUANTIDADE) AS QTD_TOTAL

FROM NOTAS_FISCAIS NF

INNER JOIN ITENS_NOTAS_FISCAIS INF

ON NF.NUMERO = INF.NUMERO
GROUP BY
NF.CPF,CONVERT(VARCHAR(7),NF.DATA_VENDA,120);




SELECT CPF, NOME, VOLUME_DE_COMPRA FROM TABELA_DE_CLIENTES;




SELECT TC.CPF,TC.NOME,TC.VOLUME_DE_COMPRA,TV.QTD_TOTAL,TV.MES_ANO,
(CASE WHEN TC.VOLUME_DE_COMPRA >= TV.QTD_TOTAL THEN 'VENDAS VÁLIDAS'
ELSE 'VENDAS INVÁLIDAS' END) AS RESULTADO

FROM TABELA_DE_CLIENTES TC

INNER JOIN (SELECT NF.CPF,CONVERT(VARCHAR(7),NF.DATA_VENDA,120) AS MES_ANO, SUM(INF.QUANTIDADE) AS QTD_TOTAL

FROM NOTAS_FISCAIS NF

INNER JOIN ITENS_NOTAS_FISCAIS INF

ON NF.NUMERO = INF.NUMERO
GROUP BY
NF.CPF,CONVERT(VARCHAR(7),NF.DATA_VENDA,120)) TV

ON TV.CPF = TC.CPF

WHERE TV.MES_ANO = '2015-01'
ORDER BY RESULTADO

;

